<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class ThanaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        DB::table('thanas')->truncate();
        Schema::enableForeignKeyConstraints();

        $thanas = [
            ['code' => 'DI1', 'name' => 'Birampur', 'status' => 1, 'district_code' => 'DI', 'created_at' => now()],
            ['code' => 'DI2', 'name' => 'Birganj', 'status' => 1, 'district_code' => 'DI', 'created_at' => now()],
            ['code' => 'DI3', 'name' => 'Birol', 'status' => 1, 'district_code' => 'DI', 'created_at' => now()],
            ['code' => 'DI4', 'name' => 'Bochaganj', 'status' => 1, 'district_code' => 'DI', 'created_at' => now()],
            ['code' => 'DI5', 'name' => 'Chirirbandar', 'status' => 1, 'district_code' => 'DI', 'created_at' => now()],
            ['code' => 'DI6', 'name' => 'Dinajpur Sadar', 'status' => 1, 'district_code' => 'DI', 'created_at' => now()],
            ['code' => 'DI7', 'name' => 'Fulbari', 'status' => 1, 'district_code' => 'DI', 'created_at' => now()],
            ['code' => 'DI8', 'name' => 'Ghoraghat', 'status' => 1, 'district_code' => 'DI', 'created_at' => now()],
            ['code' => 'DI9', 'name' => 'Hakimpur', 'status' => 1, 'district_code' => 'DI', 'created_at' => now()],
            ['code' => 'DI10', 'name' => 'Kaharol', 'status' => 1, 'district_code' => 'DI', 'created_at' => now()],
            ['code' => 'DI11', 'name' => 'Khanshama', 'status' => 1, 'district_code' => 'DI', 'created_at' => now()],
            ['code' => 'DI12', 'name' => 'Nawabganj', 'status' => 1, 'district_code' => 'DI', 'created_at' => now()],
            ['code' => 'DI13', 'name' => 'Parbatipur', 'status' => 1, 'district_code' => 'DI', 'created_at' => now()],
            ['code' => 'GA1', 'name' => 'Fulchari', 'status' => 1, 'district_code' => 'GA', 'created_at' => now()],
            ['code' => 'GA2', 'name' => 'Gaibandha Sadar', 'status' => 1, 'district_code' => 'GA', 'created_at' => now()],
            ['code' => 'GA3', 'name' => 'Gobindaganj', 'status' => 1, 'district_code' => 'GA', 'created_at' => now()],
            ['code' => 'GA4', 'name' => 'Palashbari', 'status' => 1, 'district_code' => 'GA', 'created_at' => now()],
            ['code' => 'GA5', 'name' => 'Sadullapur', 'status' => 1, 'district_code' => 'GA', 'created_at' => now()],
            ['code' => 'GA6', 'name' => 'Saghata', 'status' => 1, 'district_code' => 'GA', 'created_at' => now()],
            ['code' => 'GA7', 'name' => 'Sundarganj', 'status' => 1, 'district_code' => 'GA', 'created_at' => now()],
            ['code' => 'KU1', 'name' => 'Bhurungamari', 'status' => 1, 'district_code' => 'KU', 'created_at' => now()],
            ['code' => 'KU2', 'name' => 'Chilmari', 'status' => 1, 'district_code' => 'KU', 'created_at' => now()],
            ['code' => 'KU3', 'name' => 'Fulbari', 'status' => 1, 'district_code' => 'KU', 'created_at' => now()],
            ['code' => 'KU4', 'name' => 'Kurigram Sadar', 'status' => 1, 'district_code' => 'KU', 'created_at' => now()],
            ['code' => 'KU5', 'name' => 'Nageswari', 'status' => 1, 'district_code' => 'KU', 'created_at' => now()],
            ['code' => 'KU6', 'name' => 'Rajarhat', 'status' => 1, 'district_code' => 'KU', 'created_at' => now()],
            ['code' => 'KU7', 'name' => 'Rajibpur', 'status' => 1, 'district_code' => 'KU', 'created_at' => now()],
            ['code' => 'KU8', 'name' => 'Rowmari', 'status' => 1, 'district_code' => 'KU', 'created_at' => now()],
            ['code' => 'KU9', 'name' => 'Ulipur', 'status' => 1, 'district_code' => 'KU', 'created_at' => now()],
            ['code' => 'LA1', 'name' => 'Aditmari', 'status' => 1, 'district_code' => 'LA', 'created_at' => now()],
            ['code' => 'LA2', 'name' => 'Hatibandha', 'status' => 1, 'district_code' => 'LA', 'created_at' => now()],
            ['code' => 'LA3', 'name' => 'Kaliganj', 'status' => 1, 'district_code' => 'LA', 'created_at' => now()],
            ['code' => 'LA4', 'name' => 'Lalmonirhat Sadar', 'status' => 1, 'district_code' => 'LA', 'created_at' => now()],
            ['code' => 'LA5', 'name' => 'Patgram', 'status' => 1, 'district_code' => 'LA', 'created_at' => now()],
            ['code' => 'NI1', 'name' => 'Dimla', 'status' => 1, 'district_code' => 'NI', 'created_at' => now()],
            ['code' => 'NI2', 'name' => 'Domar', 'status' => 1, 'district_code' => 'NI', 'created_at' => now()],
            ['code' => 'NI3', 'name' => 'Jaldhaka', 'status' => 1, 'district_code' => 'NI', 'created_at' => now()],
            ['code' => 'NI4', 'name' => 'Kishoreganj', 'status' => 1, 'district_code' => 'NI', 'created_at' => now()],
            ['code' => 'NI5', 'name' => 'Nilphamari Sadar', 'status' => 1, 'district_code' => 'NI', 'created_at' => now()],
            ['code' => 'NI6', 'name' => 'Sayedpur', 'status' => 1, 'district_code' => 'NI', 'created_at' => now()],
            ['code' => 'NI7', 'name' => 'Syedpur Police Outpost', 'status' => 1, 'district_code' => 'NI', 'created_at' => now()],
            ['code' => 'PA1', 'name' => 'Atwari', 'status' => 1, 'district_code' => 'PA', 'created_at' => now()],
            ['code' => 'PA2', 'name' => 'Boda', 'status' => 1, 'district_code' => 'PA', 'created_at' => now()],
            ['code' => 'PA3', 'name' => 'Debiganj', 'status' => 1, 'district_code' => 'PA', 'created_at' => now()],
            ['code' => 'PA4', 'name' => 'Panchagarh Sadar', 'status' => 1, 'district_code' => 'PA', 'created_at' => now()],
            ['code' => 'PA5', 'name' => 'Tetulia', 'status' => 1, 'district_code' => 'PA', 'created_at' => now()],
            ['code' => 'TH1', 'name' => 'Baliadangi', 'status' => 1, 'district_code' => 'TH', 'created_at' => now()],
            ['code' => 'TH2', 'name' => 'Haripur', 'status' => 1, 'district_code' => 'TH', 'created_at' => now()],
            ['code' => 'TH3', 'name' => 'Pirganj', 'status' => 1, 'district_code' => 'TH', 'created_at' => now()],
            ['code' => 'TH4', 'name' => 'Ranisankail', 'status' => 1, 'district_code' => 'TH', 'created_at' => now()],
            ['code' => 'TH5', 'name' => 'Thakurgaon Sadar', 'status' => 1, 'district_code' => 'TH', 'created_at' => now()],
            ['code' => 'RA1', 'name' => 'Badarganj', 'status' => 1, 'district_code' => 'RA', 'created_at' => now()],
            ['code' => 'RA2', 'name' => 'Gangachara', 'status' => 1, 'district_code' => 'RA', 'created_at' => now()],
            ['code' => 'RA3', 'name' => 'Kaunia', 'status' => 1, 'district_code' => 'RA', 'created_at' => now()],
            ['code' => 'RA4', 'name' => 'Mithapukur', 'status' => 1, 'district_code' => 'RA', 'created_at' => now()],
            ['code' => 'RA5', 'name' => 'Pirgacha', 'status' => 1, 'district_code' => 'RA', 'created_at' => now()],
            ['code' => 'RA6', 'name' => 'Pirganj', 'status' => 1, 'district_code' => 'RA', 'created_at' => now()],
            ['code' => 'RA7', 'name' => 'Rangpur Sadar', 'status' => 1, 'district_code' => 'RA', 'created_at' => now()],
            ['code' => 'RA8', 'name' => 'Taraganj', 'status' => 1, 'district_code' => 'RA', 'created_at' => now()],
            ['code' => 'RA9', 'name' => 'Kotwali', 'status' => 1, 'district_code' => 'RA', 'created_at' => now()],
            ['code' => 'RA10', 'name' => 'Parshuram', 'status' => 1, 'district_code' => 'RA', 'created_at' => now()],
            ['code' => 'RA11', 'name' => 'Haragach', 'status' => 1, 'district_code' => 'RA', 'created_at' => now()],
            ['code' => 'RA12', 'name' => 'Tajhat', 'status' => 1, 'district_code' => 'RA', 'created_at' => now()],
            ['code' => 'RA13', 'name' => 'Mahiganj', 'status' => 1, 'district_code' => 'RA', 'created_at' => now()],
            ['code' => 'RA14', 'name' => 'Hajirhat', 'status' => 1, 'district_code' => 'RA', 'created_at' => now()],
            ['code' => 'HA1', 'name' => 'Azmiriganj', 'status' => 1, 'district_code' => 'HA', 'created_at' => now()],
            ['code' => 'HA2', 'name' => 'Bahubal', 'status' => 1, 'district_code' => 'HA', 'created_at' => now()],
            ['code' => 'HA3', 'name' => 'Baniachong', 'status' => 1, 'district_code' => 'HA', 'created_at' => now()],
            ['code' => 'HA4', 'name' => 'Chunarughat', 'status' => 1, 'district_code' => 'HA', 'created_at' => now()],
            ['code' => 'HA5', 'name' => 'Habiganj Sadar', 'status' => 1, 'district_code' => 'HA', 'created_at' => now()],
            ['code' => 'HA6', 'name' => 'Lakhai', 'status' => 1, 'district_code' => 'HA', 'created_at' => now()],
            ['code' => 'HA7', 'name' => 'Madhabpur', 'status' => 1, 'district_code' => 'HA', 'created_at' => now()],
            ['code' => 'HA8', 'name' => 'Nabiganj', 'status' => 1, 'district_code' => 'HA', 'created_at' => now()],
            ['code' => 'HA9', 'name' => 'Sayestaganj', 'status' => 1, 'district_code' => 'HA', 'created_at' => now()],
            ['code' => 'MO1', 'name' => 'Barlekha', 'status' => 1, 'district_code' => 'MO', 'created_at' => now()],
            ['code' => 'MO2', 'name' => 'Juri', 'status' => 1, 'district_code' => 'MO', 'created_at' => now()],
            ['code' => 'MO3', 'name' => 'Kamalganj', 'status' => 1, 'district_code' => 'MO', 'created_at' => now()],
            ['code' => 'MO4', 'name' => 'Kulaura', 'status' => 1, 'district_code' => 'MO', 'created_at' => now()],
            ['code' => 'MO5', 'name' => 'Moulvibazar Sadar', 'status' => 1, 'district_code' => 'MO', 'created_at' => now()],
            ['code' => 'MO6', 'name' => 'Rajnagar', 'status' => 1, 'district_code' => 'MO', 'created_at' => now()],
            ['code' => 'MO7', 'name' => 'Sreemangal', 'status' => 1, 'district_code' => 'MO', 'created_at' => now()],
            ['code' => 'SU1', 'name' => 'Biswamvarpur', 'status' => 1, 'district_code' => 'SU', 'created_at' => now()],
            ['code' => 'SU2', 'name' => 'Chatak', 'status' => 1, 'district_code' => 'SU', 'created_at' => now()],
            ['code' => 'SU3', 'name' => 'Dakhin Sunamganj', 'status' => 1, 'district_code' => 'SU', 'created_at' => now()],
            ['code' => 'SU4', 'name' => 'Derai', 'status' => 1, 'district_code' => 'SU', 'created_at' => now()],
            ['code' => 'SU5', 'name' => 'Dharmapasha', 'status' => 1, 'district_code' => 'SU', 'created_at' => now()],
            ['code' => 'SU6', 'name' => 'Doarabazar', 'status' => 1, 'district_code' => 'SU', 'created_at' => now()],
            ['code' => 'SU7', 'name' => 'Jagannathpur', 'status' => 1, 'district_code' => 'SU', 'created_at' => now()],
            ['code' => 'SU8', 'name' => 'Jamalganj', 'status' => 1, 'district_code' => 'SU', 'created_at' => now()],
            ['code' => 'SU9', 'name' => 'Sulna', 'status' => 1, 'district_code' => 'SU', 'created_at' => now()],
            ['code' => 'SU10', 'name' => 'Sunamganj Sadar', 'status' => 1, 'district_code' => 'SU', 'created_at' => now()],
            ['code' => 'SU11', 'name' => 'Tahirpur', 'status' => 1, 'district_code' => 'SU', 'created_at' => now()],
            ['code' => 'SY1', 'name' => 'Balaganj', 'status' => 1, 'district_code' => 'SY', 'created_at' => now()],
            ['code' => 'SY2', 'name' => 'Beanibazar', 'status' => 1, 'district_code' => 'SY', 'created_at' => now()],
            ['code' => 'SY3', 'name' => 'Biswanath', 'status' => 1, 'district_code' => 'SY', 'created_at' => now()],
            ['code' => 'SY4', 'name' => 'Companiganj', 'status' => 1, 'district_code' => 'SY', 'created_at' => now()],
            ['code' => 'SY5', 'name' => 'Dakshin Surma', 'status' => 1, 'district_code' => 'SY', 'created_at' => now()],
            ['code' => 'SY6', 'name' => 'Fenchuganj', 'status' => 1, 'district_code' => 'SY', 'created_at' => now()],
            ['code' => 'SY7', 'name' => 'Golapganj', 'status' => 1, 'district_code' => 'SY', 'created_at' => now()],
            ['code' => 'SY8', 'name' => 'Gowainghat', 'status' => 1, 'district_code' => 'SY', 'created_at' => now()],
            ['code' => 'SY9', 'name' => 'Jointiapur', 'status' => 1, 'district_code' => 'SY', 'created_at' => now()],
            ['code' => 'SY10', 'name' => 'Kanaighat', 'status' => 1, 'district_code' => 'SY', 'created_at' => now()],
            ['code' => 'SY11', 'name' => 'Osmaninagar', 'status' => 1, 'district_code' => 'SY', 'created_at' => now()],
            ['code' => 'SY12', 'name' => 'Sylhet Sadar', 'status' => 1, 'district_code' => 'SY', 'created_at' => now()],
            ['code' => 'SY13', 'name' => 'Zakiganj', 'status' => 1, 'district_code' => 'SY', 'created_at' => now()],
            ['code' => 'SY14', 'name' => 'Kotwali Model', 'status' => 1, 'district_code' => 'SY', 'created_at' => now()],
            ['code' => 'SY15', 'name' => 'Jalalabad', 'status' => 1, 'district_code' => 'SY', 'created_at' => now()],
            ['code' => 'SY16', 'name' => 'Airport', 'status' => 1, 'district_code' => 'SY', 'created_at' => now()],
            ['code' => 'SY17', 'name' => 'Moglabazar', 'status' => 1, 'district_code' => 'SY', 'created_at' => now()],
            ['code' => 'SY18', 'name' => 'South Surma', 'status' => 1, 'district_code' => 'SY', 'created_at' => now()],
            ['code' => 'SY19', 'name' => 'Shah Poran (R.)', 'status' => 1, 'district_code' => 'SY', 'created_at' => now()],
            ['code' => 'BA1', 'name' => 'Amtali', 'status' => 1, 'district_code' => 'BA', 'created_at' => now()],
            ['code' => 'BA2', 'name' => 'Bamna', 'status' => 1, 'district_code' => 'BA', 'created_at' => now()],
            ['code' => 'BA3', 'name' => 'Barguna Sadar', 'status' => 1, 'district_code' => 'BA', 'created_at' => now()],
            ['code' => 'BA4', 'name' => 'Betagi', 'status' => 1, 'district_code' => 'BA', 'created_at' => now()],
            ['code' => 'BA5', 'name' => 'Patharghata', 'status' => 1, 'district_code' => 'BA', 'created_at' => now()],
            ['code' => 'BA6', 'name' => 'Taltali', 'status' => 1, 'district_code' => 'BA', 'created_at' => now()],
            ['code' => 'BH1', 'name' => 'Bhola Sadar', 'status' => 1, 'district_code' => 'BH', 'created_at' => now()],
            ['code' => 'BH2', 'name' => 'Borhanuddin', 'status' => 1, 'district_code' => 'BH', 'created_at' => now()],
            ['code' => 'BH3', 'name' => 'Charfassion', 'status' => 1, 'district_code' => 'BH', 'created_at' => now()],
            ['code' => 'BH4', 'name' => 'Daulatkhan', 'status' => 1, 'district_code' => 'BH', 'created_at' => now()],
            ['code' => 'BH5', 'name' => 'Lalmohan', 'status' => 1, 'district_code' => 'BH', 'created_at' => now()],
            ['code' => 'BH6', 'name' => 'Monpura', 'status' => 1, 'district_code' => 'BH', 'created_at' => now()],
            ['code' => 'BH7', 'name' => 'Tazumuddin', 'status' => 1, 'district_code' => 'BH', 'created_at' => now()],
            ['code' => 'JH1', 'name' => 'Jhalokathi Sadar', 'status' => 1, 'district_code' => 'JH', 'created_at' => now()],
            ['code' => 'JH2', 'name' => 'Kathalia', 'status' => 1, 'district_code' => 'JH', 'created_at' => now()],
            ['code' => 'JH3', 'name' => 'Nalchity', 'status' => 1, 'district_code' => 'JH', 'created_at' => now()],
            ['code' => 'JH4', 'name' => 'Rajapur', 'status' => 1, 'district_code' => 'JH', 'created_at' => now()],
            ['code' => 'PT1', 'name' => 'Bauphal', 'status' => 1, 'district_code' => 'PT', 'created_at' => now()],
            ['code' => 'PT2', 'name' => 'Dashmina', 'status' => 1, 'district_code' => 'PT', 'created_at' => now()],
            ['code' => 'PT3', 'name' => 'Dumki', 'status' => 1, 'district_code' => 'PT', 'created_at' => now()],
            ['code' => 'PT4', 'name' => 'Galachipa', 'status' => 1, 'district_code' => 'PT', 'created_at' => now()],
            ['code' => 'PT5', 'name' => 'Kalapara', 'status' => 1, 'district_code' => 'PT', 'created_at' => now()],
            ['code' => 'PT6', 'name' => 'Mirjaganj', 'status' => 1, 'district_code' => 'PT', 'created_at' => now()],
            ['code' => 'PT7', 'name' => 'Patuakhali Sadar', 'status' => 1, 'district_code' => 'PT', 'created_at' => now()],
            ['code' => 'PT8', 'name' => 'Rangabali', 'status' => 1, 'district_code' => 'PT', 'created_at' => now()],
            ['code' => 'PR1', 'name' => 'Bhandaria', 'status' => 1, 'district_code' => 'PR', 'created_at' => now()],
            ['code' => 'PR2', 'name' => 'Kawkhali', 'status' => 1, 'district_code' => 'PR', 'created_at' => now()],
            ['code' => 'PR3', 'name' => 'Mothbaria', 'status' => 1, 'district_code' => 'PR', 'created_at' => now()],
            ['code' => 'PR4', 'name' => 'Nazirpur', 'status' => 1, 'district_code' => 'PR', 'created_at' => now()],
            ['code' => 'PR5', 'name' => 'Nesarabad', 'status' => 1, 'district_code' => 'PR', 'created_at' => now()],
            ['code' => 'PR6', 'name' => 'Pirojpur Sadar', 'status' => 1, 'district_code' => 'PR', 'created_at' => now()],
            ['code' => 'PR7', 'name' => 'Zianagar', 'status' => 1, 'district_code' => 'PR', 'created_at' => now()],
            ['code' => 'BS1', 'name' => 'Agailjhara', 'status' => 1, 'district_code' => 'BS', 'created_at' => now()],
            ['code' => 'BS2', 'name' => 'Babuganj', 'status' => 1, 'district_code' => 'BS', 'created_at' => now()],
            ['code' => 'BS3', 'name' => 'Bakerganj', 'status' => 1, 'district_code' => 'BS', 'created_at' => now()],
            ['code' => 'BS4', 'name' => 'Banaripara', 'status' => 1, 'district_code' => 'BS', 'created_at' => now()],
            ['code' => 'BS5', 'name' => 'Barishal Sadar', 'status' => 1, 'district_code' => 'BS', 'created_at' => now()],
            ['code' => 'BS6', 'name' => 'Gouranadi', 'status' => 1, 'district_code' => 'BS', 'created_at' => now()],
            ['code' => 'BS7', 'name' => 'Hizla', 'status' => 1, 'district_code' => 'BS', 'created_at' => now()],
            ['code' => 'BS8', 'name' => 'Mehendiganj', 'status' => 1, 'district_code' => 'BS', 'created_at' => now()],
            ['code' => 'BS9', 'name' => 'Muladi', 'status' => 1, 'district_code' => 'BS', 'created_at' => now()],
            ['code' => 'BS10', 'name' => 'Uzirpur', 'status' => 1, 'district_code' => 'BS', 'created_at' => now()],
            ['code' => 'BS11', 'name' => 'Kotwali Model', 'status' => 1, 'district_code' => 'BS', 'created_at' => now()],
            ['code' => 'BS12', 'name' => 'Airport', 'status' => 1, 'district_code' => 'BS', 'created_at' => now()],
            ['code' => 'BS13', 'name' => 'Kawnia', 'status' => 1, 'district_code' => 'BS', 'created_at' => now()],
            ['code' => 'BS14', 'name' => 'Bandar', 'status' => 1, 'district_code' => 'BS', 'created_at' => now()],
            ['code' => 'BS15', 'name' => 'Rupatali', 'status' => 1, 'district_code' => 'BS', 'created_at' => now()],
            ['code' => 'BS16', 'name' => 'Barisal University', 'status' => 1, 'district_code' => 'BS', 'created_at' => now()],
            ['code' => 'BS17', 'name' => 'Char Monai', 'status' => 1, 'district_code' => 'BS', 'created_at' => now()],
            ['code' => 'BS18', 'name' => 'Kashipur', 'status' => 1, 'district_code' => 'BS', 'created_at' => now()],
            ['code' => 'BO1', 'name' => 'Adamdighi', 'status' => 1, 'district_code' => 'BO', 'created_at' => now()],
            ['code' => 'BO2', 'name' => 'Bogura Sadar', 'status' => 1, 'district_code' => 'BO', 'created_at' => now()],
            ['code' => 'BO3', 'name' => 'Dhunot', 'status' => 1, 'district_code' => 'BO', 'created_at' => now()],
            ['code' => 'BO4', 'name' => 'Dhupchancia', 'status' => 1, 'district_code' => 'BO', 'created_at' => now()],
            ['code' => 'BO5', 'name' => 'Gabtali', 'status' => 1, 'district_code' => 'BO', 'created_at' => now()],
            ['code' => 'BO6', 'name' => 'Kahaloo', 'status' => 1, 'district_code' => 'BO', 'created_at' => now()],
            ['code' => 'BO7', 'name' => 'Nandigram', 'status' => 1, 'district_code' => 'BO', 'created_at' => now()],
            ['code' => 'BO8', 'name' => 'Sariakandi', 'status' => 1, 'district_code' => 'BO', 'created_at' => now()],
            ['code' => 'BO9', 'name' => 'Shajahanpur', 'status' => 1, 'district_code' => 'BO', 'created_at' => now()],
            ['code' => 'BO10', 'name' => 'Sherpur', 'status' => 1, 'district_code' => 'BO', 'created_at' => now()],
            ['code' => 'BO11', 'name' => 'Shibganj', 'status' => 1, 'district_code' => 'BO', 'created_at' => now()],
            ['code' => 'BO12', 'name' => 'Sonatala', 'status' => 1, 'district_code' => 'BO', 'created_at' => now()],
            ['code' => 'CN1', 'name' => 'Bholahat', 'status' => 1, 'district_code' => 'CN', 'created_at' => now()],
            ['code' => 'CN2', 'name' => 'Gomostapur', 'status' => 1, 'district_code' => 'CN', 'created_at' => now()],
            ['code' => 'CN3', 'name' => 'Nachol', 'status' => 1, 'district_code' => 'CN', 'created_at' => now()],
            ['code' => 'CN4', 'name' => 'NawabganjSadar', 'status' => 1, 'district_code' => 'CN', 'created_at' => now()],
            ['code' => 'CN5', 'name' => 'Shibganj', 'status' => 1, 'district_code' => 'CN', 'created_at' => now()],
            ['code' => 'JO1', 'name' => 'Akkelpur', 'status' => 1, 'district_code' => 'JO', 'created_at' => now()],
            ['code' => 'JO2', 'name' => 'Joypurhat Sadar', 'status' => 1, 'district_code' => 'JO', 'created_at' => now()],
            ['code' => 'JO3', 'name' => 'Kalai', 'status' => 1, 'district_code' => 'JO', 'created_at' => now()],
            ['code' => 'JO4', 'name' => 'Khetlal', 'status' => 1, 'district_code' => 'JO', 'created_at' => now()],
            ['code' => 'JO5', 'name' => 'Panchbibi', 'status' => 1, 'district_code' => 'JO', 'created_at' => now()],
            ['code' => 'NA1', 'name' => 'Atrai', 'status' => 1, 'district_code' => 'NA', 'created_at' => now()],
            ['code' => 'NA2', 'name' => 'Badalgachi', 'status' => 1, 'district_code' => 'NA', 'created_at' => now()],
            ['code' => 'NA3', 'name' => 'Dhamoirhat', 'status' => 1, 'district_code' => 'NA', 'created_at' => now()],
            ['code' => 'NA4', 'name' => 'Manda', 'status' => 1, 'district_code' => 'NA', 'created_at' => now()],
            ['code' => 'NA5', 'name' => 'Mohadevpur', 'status' => 1, 'district_code' => 'NA', 'created_at' => now()],
            ['code' => 'NA6', 'name' => 'Naogaon Sadar', 'status' => 1, 'district_code' => 'NA', 'created_at' => now()],
            ['code' => 'NA7', 'name' => 'Niamatpur', 'status' => 1, 'district_code' => 'NA', 'created_at' => now()],
            ['code' => 'NA8', 'name' => 'Patnitala', 'status' => 1, 'district_code' => 'NA', 'created_at' => now()],
            ['code' => 'NA9', 'name' => 'Porsha', 'status' => 1, 'district_code' => 'NA', 'created_at' => now()],
            ['code' => 'NA10', 'name' => 'Raynagar', 'status' => 1, 'district_code' => 'NA', 'created_at' => now()],
            ['code' => 'NA11', 'name' => 'Shapahar', 'status' => 1, 'district_code' => 'NA', 'created_at' => now()],
            ['code' => 'NT1', 'name' => 'Bagatipara', 'status' => 1, 'district_code' => 'NT', 'created_at' => now()],
            ['code' => 'NT2', 'name' => 'Baraigram', 'status' => 1, 'district_code' => 'NT', 'created_at' => now()],
            ['code' => 'NT3', 'name' => 'Gurudaspur', 'status' => 1, 'district_code' => 'NT', 'created_at' => now()],
            ['code' => 'NT4', 'name' => 'Lalpur', 'status' => 1, 'district_code' => 'NT', 'created_at' => now()],
            ['code' => 'NT5', 'name' => 'Naldanga', 'status' => 1, 'district_code' => 'NT', 'created_at' => now()],
            ['code' => 'NT6', 'name' => 'Natore Sadar', 'status' => 1, 'district_code' => 'NT', 'created_at' => now()],
            ['code' => 'NT7', 'name' => 'Singra', 'status' => 1, 'district_code' => 'NT', 'created_at' => now()],
            ['code' => 'PB1', 'name' => 'Atghoria', 'status' => 1, 'district_code' => 'PB', 'created_at' => now()],
            ['code' => 'PB2', 'name' => 'Bera', 'status' => 1, 'district_code' => 'PB', 'created_at' => now()],
            ['code' => 'PB3', 'name' => 'Bhangura', 'status' => 1, 'district_code' => 'PB', 'created_at' => now()],
            ['code' => 'PB4', 'name' => 'Chatmohar', 'status' => 1, 'district_code' => 'PB', 'created_at' => now()],
            ['code' => 'PB5', 'name' => 'Faridpur', 'status' => 1, 'district_code' => 'PB', 'created_at' => now()],
            ['code' => 'PB6', 'name' => 'Ishwardi', 'status' => 1, 'district_code' => 'PB', 'created_at' => now()],
            ['code' => 'PB7', 'name' => 'Pabna Sadar', 'status' => 1, 'district_code' => 'PB', 'created_at' => now()],
            ['code' => 'PB8', 'name' => 'Santhia', 'status' => 1, 'district_code' => 'PB', 'created_at' => now()],
            ['code' => 'PB9', 'name' => 'Ataikula', 'status' => 1, 'district_code' => 'PB', 'created_at' => now()],
            ['code' => 'PB10', 'name' => 'Sujanagar', 'status' => 1, 'district_code' => 'PB', 'created_at' => now()],
            ['code' => 'SI1', 'name' => 'Belkuchi', 'status' => 1, 'district_code' => 'SI', 'created_at' => now()],
            ['code' => 'SI2', 'name' => 'Chowhali', 'status' => 1, 'district_code' => 'SI', 'created_at' => now()],
            ['code' => 'SI3', 'name' => 'Kamarkhand', 'status' => 1, 'district_code' => 'SI', 'created_at' => now()],
            ['code' => 'SI4', 'name' => 'Kazipur', 'status' => 1, 'district_code' => 'SI', 'created_at' => now()],
            ['code' => 'SI5', 'name' => 'Raiganj', 'status' => 1, 'district_code' => 'SI', 'created_at' => now()],
            ['code' => 'SI6', 'name' => 'Shahzadpur', 'status' => 1, 'district_code' => 'SI', 'created_at' => now()],
            ['code' => 'SI7', 'name' => 'Sirajganj Sadar', 'status' => 1, 'district_code' => 'SI', 'created_at' => now()],
            ['code' => 'SI8', 'name' => 'Tarash', 'status' => 1, 'district_code' => 'SI', 'created_at' => now()],
            ['code' => 'SI9', 'name' => 'Jamuna Bridge West', 'status' => 1, 'district_code' => 'SI', 'created_at' => now()],
            ['code' => 'SI10', 'name' => 'Salanga', 'status' => 1, 'district_code' => 'SI', 'created_at' => now()],
            ['code' => 'SI11', 'name' => 'Enayetpur', 'status' => 1, 'district_code' => 'SI', 'created_at' => now()],
            ['code' => 'SI12', 'name' => 'Ullapara', 'status' => 1, 'district_code' => 'SI', 'created_at' => now()],
            ['code' => 'RJ1', 'name' => 'Bagha', 'status' => 1, 'district_code' => 'RJ', 'created_at' => now()],
            ['code' => 'RJ2', 'name' => 'Bagmara', 'status' => 1, 'district_code' => 'RJ', 'created_at' => now()],
            ['code' => 'RJ3', 'name' => 'Charghat', 'status' => 1, 'district_code' => 'RJ', 'created_at' => now()],
            ['code' => 'RJ4', 'name' => 'Durgapur', 'status' => 1, 'district_code' => 'RJ', 'created_at' => now()],
            ['code' => 'RJ5', 'name' => 'Godagari', 'status' => 1, 'district_code' => 'RJ', 'created_at' => now()],
            ['code' => 'RJ6', 'name' => 'Mohanpur', 'status' => 1, 'district_code' => 'RJ', 'created_at' => now()],
            ['code' => 'RJ7', 'name' => 'Paba', 'status' => 1, 'district_code' => 'RJ', 'created_at' => now()],
            ['code' => 'RJ8', 'name' => 'Puthia', 'status' => 1, 'district_code' => 'RJ', 'created_at' => now()],
            ['code' => 'RJ9', 'name' => 'Tanore', 'status' => 1, 'district_code' => 'RJ', 'created_at' => now()],
            ['code' => 'RJ10', 'name' => 'Boalia', 'status' => 1, 'district_code' => 'RJ', 'created_at' => now()],
            ['code' => 'RJ11', 'name' => 'Rajpara', 'status' => 1, 'district_code' => 'RJ', 'created_at' => now()],
            ['code' => 'RJ12', 'name' => 'Motihar', 'status' => 1, 'district_code' => 'RJ', 'created_at' => now()],
            ['code' => 'RJ13', 'name' => 'Shah Maqdum', 'status' => 1, 'district_code' => 'RJ', 'created_at' => now()],
            ['code' => 'RJ14', 'name' => 'Chandrima', 'status' => 1, 'district_code' => 'RJ', 'created_at' => now()],
            ['code' => 'RJ15', 'name' => 'Kasiadanga', 'status' => 1, 'district_code' => 'RJ', 'created_at' => now()],
            ['code' => 'RJ16', 'name' => 'Katakhali', 'status' => 1, 'district_code' => 'RJ', 'created_at' => now()],
            ['code' => 'RJ17', 'name' => 'Belpukur', 'status' => 1, 'district_code' => 'RJ', 'created_at' => now()],
            ['code' => 'RJ18', 'name' => 'Airport', 'status' => 1, 'district_code' => 'RJ', 'created_at' => now()],
            ['code' => 'RJ19', 'name' => 'Karnahar', 'status' => 1, 'district_code' => 'RJ', 'created_at' => now()],
            ['code' => 'RJ20', 'name' => 'Damkura', 'status' => 1, 'district_code' => 'RJ', 'created_at' => now()],
            ['code' => 'BG1', 'name' => 'Bagerhat Sadar', 'status' => 1, 'district_code' => 'BG', 'created_at' => now()],
            ['code' => 'BG2', 'name' => 'Chitalmari', 'status' => 1, 'district_code' => 'BG', 'created_at' => now()],
            ['code' => 'BG3', 'name' => 'Fakirhat', 'status' => 1, 'district_code' => 'BG', 'created_at' => now()],
            ['code' => 'BG4', 'name' => 'Kachua', 'status' => 1, 'district_code' => 'BG', 'created_at' => now()],
            ['code' => 'BG5', 'name' => 'Mollahat', 'status' => 1, 'district_code' => 'BG', 'created_at' => now()],
            ['code' => 'BG6', 'name' => 'Mongla', 'status' => 1, 'district_code' => 'BG', 'created_at' => now()],
            ['code' => 'BG7', 'name' => 'Morrelganj', 'status' => 1, 'district_code' => 'BG', 'created_at' => now()],
            ['code' => 'BG8', 'name' => 'Rampal', 'status' => 1, 'district_code' => 'BG', 'created_at' => now()],
            ['code' => 'BG9', 'name' => 'Sharankhola', 'status' => 1, 'district_code' => 'BG', 'created_at' => now()],
            ['code' => 'CH1', 'name' => 'Alamdanga', 'status' => 1, 'district_code' => 'CH', 'created_at' => now()],
            ['code' => 'CH2', 'name' => 'Chuadanga Sadar', 'status' => 1, 'district_code' => 'CH', 'created_at' => now()],
            ['code' => 'CH3', 'name' => 'Damurhuda', 'status' => 1, 'district_code' => 'CH', 'created_at' => now()],
            ['code' => 'CH4', 'name' => 'Jibannagar', 'status' => 1, 'district_code' => 'CH', 'created_at' => now()],
            ['code' => 'JA1', 'name' => 'Abhoynagar', 'status' => 1, 'district_code' => 'JA', 'created_at' => now()],
            ['code' => 'JA2', 'name' => 'Bagherpara', 'status' => 1, 'district_code' => 'JA', 'created_at' => now()],
            ['code' => 'JA3', 'name' => 'Chowgacha', 'status' => 1, 'district_code' => 'JA', 'created_at' => now()],
            ['code' => 'JA4', 'name' => 'Jashore Sadar', 'status' => 1, 'district_code' => 'JA', 'created_at' => now()],
            ['code' => 'JA5', 'name' => 'Jhikargacha', 'status' => 1, 'district_code' => 'JA', 'created_at' => now()],
            ['code' => 'JA6', 'name' => 'Keshabpur', 'status' => 1, 'district_code' => 'JA', 'created_at' => now()],
            ['code' => 'JA7', 'name' => 'Monirampur', 'status' => 1, 'district_code' => 'JA', 'created_at' => now()],
            ['code' => 'JA8', 'name' => 'Sarsha', 'status' => 1, 'district_code' => 'JA', 'created_at' => now()],
            ['code' => 'JN1', 'name' => 'Harinakunda', 'status' => 1, 'district_code' => 'JN', 'created_at' => now()],
            ['code' => 'JN2', 'name' => 'Jhenaidah Sadar', 'status' => 1, 'district_code' => 'JN', 'created_at' => now()],
            ['code' => 'JN3', 'name' => 'Kaliganj', 'status' => 1, 'district_code' => 'JN', 'created_at' => now()],
            ['code' => 'JN4', 'name' => 'Kotchandpur', 'status' => 1, 'district_code' => 'JN', 'created_at' => now()],
            ['code' => 'JN5', 'name' => 'Moheshpur', 'status' => 1, 'district_code' => 'JN', 'created_at' => now()],
            ['code' => 'JN6', 'name' => 'Shailkupa', 'status' => 1, 'district_code' => 'JN', 'created_at' => now()],
            ['code' => 'KS1', 'name' => 'Islami University', 'status' => 1, 'district_code' => 'KS', 'created_at' => now()],
            ['code' => 'KS2', 'name' => 'Bheramara', 'status' => 1, 'district_code' => 'KS', 'created_at' => now()],
            ['code' => 'KS3', 'name' => 'Daulatpur', 'status' => 1, 'district_code' => 'KS', 'created_at' => now()],
            ['code' => 'KS4', 'name' => 'Khoksha', 'status' => 1, 'district_code' => 'KS', 'created_at' => now()],
            ['code' => 'KS5', 'name' => 'Kumarkhali', 'status' => 1, 'district_code' => 'KS', 'created_at' => now()],
            ['code' => 'KS6', 'name' => 'Kushtia Sadar', 'status' => 1, 'district_code' => 'KS', 'created_at' => now()],
            ['code' => 'KS7', 'name' => 'Mirpur', 'status' => 1, 'district_code' => 'KS', 'created_at' => now()],
            ['code' => 'MA1', 'name' => 'MaguraSadar', 'status' => 1, 'district_code' => 'MA', 'created_at' => now()],
            ['code' => 'MA2', 'name' => 'Mohammadpur', 'status' => 1, 'district_code' => 'MA', 'created_at' => now()],
            ['code' => 'MA3', 'name' => 'Salikha', 'status' => 1, 'district_code' => 'MA', 'created_at' => now()],
            ['code' => 'MA4', 'name' => 'Sreepur', 'status' => 1, 'district_code' => 'MA', 'created_at' => now()],
            ['code' => 'ME1', 'name' => 'Gangni', 'status' => 1, 'district_code' => 'ME', 'created_at' => now()],
            ['code' => 'ME2', 'name' => 'Meherpur Sadar', 'status' => 1, 'district_code' => 'ME', 'created_at' => now()],
            ['code' => 'ME3', 'name' => 'Mujib Nagar', 'status' => 1, 'district_code' => 'ME', 'created_at' => now()],
            ['code' => 'NL1', 'name' => 'Naragati', 'status' => 1, 'district_code' => 'NL', 'created_at' => now()],
            ['code' => 'NL2', 'name' => 'Kalia', 'status' => 1, 'district_code' => 'NL', 'created_at' => now()],
            ['code' => 'NL3', 'name' => 'Lohagara', 'status' => 1, 'district_code' => 'NL', 'created_at' => now()],
            ['code' => 'NL4', 'name' => 'Narail Sadar', 'status' => 1, 'district_code' => 'NL', 'created_at' => now()],
            ['code' => 'SK1', 'name' => 'Assasuni', 'status' => 1, 'district_code' => 'SK', 'created_at' => now()],
            ['code' => 'SK2', 'name' => 'Debhata', 'status' => 1, 'district_code' => 'SK', 'created_at' => now()],
            ['code' => 'SK3', 'name' => 'Kalaroa', 'status' => 1, 'district_code' => 'SK', 'created_at' => now()],
            ['code' => 'SK4', 'name' => 'Kaliganj', 'status' => 1, 'district_code' => 'SK', 'created_at' => now()],
            ['code' => 'SK5', 'name' => 'Satkhira Sadar', 'status' => 1, 'district_code' => 'SK', 'created_at' => now()],
            ['code' => 'SK6', 'name' => 'Shyamnagar', 'status' => 1, 'district_code' => 'SK', 'created_at' => now()],
            ['code' => 'SK7', 'name' => 'Tala', 'status' => 1, 'district_code' => 'SK', 'created_at' => now()],
            ['code' => 'KH1', 'name' => 'Batiaghata', 'status' => 1, 'district_code' => 'KH', 'created_at' => now()],
            ['code' => 'KH2', 'name' => 'Dacope', 'status' => 1, 'district_code' => 'KH', 'created_at' => now()],
            ['code' => 'KH3', 'name' => 'Dighalia', 'status' => 1, 'district_code' => 'KH', 'created_at' => now()],
            ['code' => 'KH4', 'name' => 'Dumuria', 'status' => 1, 'district_code' => 'KH', 'created_at' => now()],
            ['code' => 'KH5', 'name' => 'Koira', 'status' => 1, 'district_code' => 'KH', 'created_at' => now()],
            ['code' => 'KH6', 'name' => 'Paikgacha', 'status' => 1, 'district_code' => 'KH', 'created_at' => now()],
            ['code' => 'KH7', 'name' => 'Phultala', 'status' => 1, 'district_code' => 'KH', 'created_at' => now()],
            ['code' => 'KH8', 'name' => 'Rupsa', 'status' => 1, 'district_code' => 'KH', 'created_at' => now()],
            ['code' => 'KH9', 'name' => 'Terokhada', 'status' => 1, 'district_code' => 'KH', 'created_at' => now()],
            ['code' => 'KH10', 'name' => 'Khulna Sadar', 'status' => 1, 'district_code' => 'KH', 'created_at' => now()],
            ['code' => 'KH11', 'name' => 'Sonadanga', 'status' => 1, 'district_code' => 'KH', 'created_at' => now()],
            ['code' => 'KH12', 'name' => 'Daulatpur', 'status' => 1, 'district_code' => 'KH', 'created_at' => now()],
            ['code' => 'KH13', 'name' => 'Khalishpur', 'status' => 1, 'district_code' => 'KH', 'created_at' => now()],
            ['code' => 'KH14', 'name' => 'Khan Jahan Ali', 'status' => 1, 'district_code' => 'KH', 'created_at' => now()],
            ['code' => 'KH15', 'name' => 'Labanchara', 'status' => 1, 'district_code' => 'KH', 'created_at' => now()],
            ['code' => 'KH16', 'name' => 'Harintana', 'status' => 1, 'district_code' => 'KH', 'created_at' => now()],
            ['code' => 'KH17', 'name' => 'Aranghata', 'status' => 1, 'district_code' => 'KH', 'created_at' => now()],
            ['code' => 'BR1', 'name' => 'Akhaura', 'status' => 1, 'district_code' => 'BR', 'created_at' => now()],
            ['code' => 'BR2', 'name' => 'Ashuganj', 'status' => 1, 'district_code' => 'BR', 'created_at' => now()],
            ['code' => 'BR3', 'name' => 'Brahmanbaria Sadar', 'status' => 1, 'district_code' => 'BR', 'created_at' => now()],
            ['code' => 'BR4', 'name' => 'Bancharampur', 'status' => 1, 'district_code' => 'BR', 'created_at' => now()],
            ['code' => 'BR5', 'name' => 'Bijoynagar', 'status' => 1, 'district_code' => 'BR', 'created_at' => now()],
            ['code' => 'BR6', 'name' => 'Kasba', 'status' => 1, 'district_code' => 'BR', 'created_at' => now()],
            ['code' => 'BR7', 'name' => 'Nabinagar', 'status' => 1, 'district_code' => 'BR', 'created_at' => now()],
            ['code' => 'BR8', 'name' => 'Nasirnagar', 'status' => 1, 'district_code' => 'BR', 'created_at' => now()],
            ['code' => 'BR9', 'name' => 'Sarail', 'status' => 1, 'district_code' => 'BR', 'created_at' => now()],
            ['code' => 'BB1', 'name' => 'Alikadam', 'status' => 1, 'district_code' => 'BB', 'created_at' => now()],
            ['code' => 'BB2', 'name' => 'Bandarban-Sadar', 'status' => 1, 'district_code' => 'BB', 'created_at' => now()],
            ['code' => 'BB3', 'name' => 'Lama', 'status' => 1, 'district_code' => 'BB', 'created_at' => now()],
            ['code' => 'BB4', 'name' => 'Naikhyongchari', 'status' => 1, 'district_code' => 'BB', 'created_at' => now()],
            ['code' => 'BB5', 'name' => 'Rowangchari', 'status' => 1, 'district_code' => 'BB', 'created_at' => now()],
            ['code' => 'BB6', 'name' => 'Ruma', 'status' => 1, 'district_code' => 'BB', 'created_at' => now()],
            ['code' => 'BB7', 'name' => 'Thanchi', 'status' => 1, 'district_code' => 'BB', 'created_at' => now()],
            ['code' => 'CP1', 'name' => 'Chandpur Sadar', 'status' => 1, 'district_code' => 'CP', 'created_at' => now()],
            ['code' => 'CP2', 'name' => 'Faridganj', 'status' => 1, 'district_code' => 'CP', 'created_at' => now()],
            ['code' => 'CP3', 'name' => 'Haimchar', 'status' => 1, 'district_code' => 'CP', 'created_at' => now()],
            ['code' => 'CP4', 'name' => 'Haziganj', 'status' => 1, 'district_code' => 'CP', 'created_at' => now()],
            ['code' => 'CP5', 'name' => 'Kachua', 'status' => 1, 'district_code' => 'CP', 'created_at' => now()],
            ['code' => 'CP6', 'name' => 'Matlab (Dakshin)', 'status' => 1, 'district_code' => 'CP', 'created_at' => now()],
            ['code' => 'CP7', 'name' => 'Matlab (Uttar)', 'status' => 1, 'district_code' => 'CP', 'created_at' => now()],
            ['code' => 'CP8', 'name' => 'Shahrasti', 'status' => 1, 'district_code' => 'CP', 'created_at' => now()],
            ['code' => 'CU1', 'name' => 'Barura', 'status' => 1, 'district_code' => 'CU', 'created_at' => now()],
            ['code' => 'CU2', 'name' => 'Brahmanpara', 'status' => 1, 'district_code' => 'CU', 'created_at' => now()],
            ['code' => 'CU3', 'name' => 'Burichong', 'status' => 1, 'district_code' => 'CU', 'created_at' => now()],
            ['code' => 'CU4', 'name' => 'Chandina', 'status' => 1, 'district_code' => 'CU', 'created_at' => now()],
            ['code' => 'CU5', 'name' => 'Chouddagram', 'status' => 1, 'district_code' => 'CU', 'created_at' => now()],
            ['code' => 'CU6', 'name' => 'Cumilla-Sadar', 'status' => 1, 'district_code' => 'CU', 'created_at' => now()],
            ['code' => 'CU7', 'name' => 'Cumilla-S Daksin', 'status' => 1, 'district_code' => 'CU', 'created_at' => now()],
            ['code' => 'CU8', 'name' => 'Daudkandi', 'status' => 1, 'district_code' => 'CU', 'created_at' => now()],
            ['code' => 'CU9', 'name' => 'Debidwar', 'status' => 1, 'district_code' => 'CU', 'created_at' => now()],
            ['code' => 'CU10', 'name' => 'Homna', 'status' => 1, 'district_code' => 'CU', 'created_at' => now()],
            ['code' => 'CU11', 'name' => 'Laksham', 'status' => 1, 'district_code' => 'CU', 'created_at' => now()],
            ['code' => 'CU12', 'name' => 'Lalmai', 'status' => 1, 'district_code' => 'CU', 'created_at' => now()],
            ['code' => 'CU13', 'name' => 'Meghna', 'status' => 1, 'district_code' => 'CU', 'created_at' => now()],
            ['code' => 'CU14', 'name' => 'Monohorganj', 'status' => 1, 'district_code' => 'CU', 'created_at' => now()],
            ['code' => 'CU15', 'name' => 'Muradnagar', 'status' => 1, 'district_code' => 'CU', 'created_at' => now()],
            ['code' => 'CU16', 'name' => 'Nangalkot', 'status' => 1, 'district_code' => 'CU', 'created_at' => now()],
            ['code' => 'CU17', 'name' => 'Titas', 'status' => 1, 'district_code' => 'CU', 'created_at' => now()],
            ['code' => 'FE1', 'name' => 'Chhagalniya', 'status' => 1, 'district_code' => 'FE', 'created_at' => now()],
            ['code' => 'FE2', 'name' => 'Daganbhuiyan', 'status' => 1, 'district_code' => 'FE', 'created_at' => now()],
            ['code' => 'FE3', 'name' => 'FeniSadar', 'status' => 1, 'district_code' => 'FE', 'created_at' => now()],
            ['code' => 'FE4', 'name' => 'Fulgazi', 'status' => 1, 'district_code' => 'FE', 'created_at' => now()],
            ['code' => 'FE5', 'name' => 'Porshuram', 'status' => 1, 'district_code' => 'FE', 'created_at' => now()],
            ['code' => 'FE6', 'name' => 'Sonagazi', 'status' => 1, 'district_code' => 'FE', 'created_at' => now()],
            ['code' => 'KC1', 'name' => 'Dighinala', 'status' => 1, 'district_code' => 'KC', 'created_at' => now()],
            ['code' => 'KC2', 'name' => 'Guimara', 'status' => 1, 'district_code' => 'KC', 'created_at' => now()],
            ['code' => 'KC3', 'name' => 'Khagrachari Sadar', 'status' => 1, 'district_code' => 'KC', 'created_at' => now()],
            ['code' => 'KC4', 'name' => 'Laxmichari', 'status' => 1, 'district_code' => 'KC', 'created_at' => now()],
            ['code' => 'KC5', 'name' => 'Mahalchari', 'status' => 1, 'district_code' => 'KC', 'created_at' => now()],
            ['code' => 'KC6', 'name' => 'Manikchari', 'status' => 1, 'district_code' => 'KC', 'created_at' => now()],
            ['code' => 'KC7', 'name' => 'Matiranga', 'status' => 1, 'district_code' => 'KC', 'created_at' => now()],
            ['code' => 'KC8', 'name' => 'Panchari', 'status' => 1, 'district_code' => 'KC', 'created_at' => now()],
            ['code' => 'KC9', 'name' => 'Ramgarh', 'status' => 1, 'district_code' => 'KC', 'created_at' => now()],
            ['code' => 'LX1', 'name' => 'Komol Nagar', 'status' => 1, 'district_code' => 'LX', 'created_at' => now()],
            ['code' => 'LX2', 'name' => 'Laxmipur Sadar', 'status' => 1, 'district_code' => 'LX', 'created_at' => now()],
            ['code' => 'LX3', 'name' => 'Raipur', 'status' => 1, 'district_code' => 'LX', 'created_at' => now()],
            ['code' => 'LX4', 'name' => 'Ramganj', 'status' => 1, 'district_code' => 'LX', 'created_at' => now()],
            ['code' => 'LX5', 'name' => 'Ramgati', 'status' => 1, 'district_code' => 'LX', 'created_at' => now()],
            ['code' => 'NO1', 'name' => 'Begumganj', 'status' => 1, 'district_code' => 'NO', 'created_at' => now()],
            ['code' => 'NO2', 'name' => 'Chatkhil', 'status' => 1, 'district_code' => 'NO', 'created_at' => now()],
            ['code' => 'NO3', 'name' => 'Companiganj', 'status' => 1, 'district_code' => 'NO', 'created_at' => now()],
            ['code' => 'NO4', 'name' => 'Hatiya', 'status' => 1, 'district_code' => 'NO', 'created_at' => now()],
            ['code' => 'NO5', 'name' => 'Kabir Hat', 'status' => 1, 'district_code' => 'NO', 'created_at' => now()],
            ['code' => 'NO6', 'name' => 'Noakhali Sadar', 'status' => 1, 'district_code' => 'NO', 'created_at' => now()],
            ['code' => 'NO7', 'name' => 'Senbag', 'status' => 1, 'district_code' => 'NO', 'created_at' => now()],
            ['code' => 'NO8', 'name' => 'Sonaimuri', 'status' => 1, 'district_code' => 'NO', 'created_at' => now()],
            ['code' => 'NO9', 'name' => 'Subarna Char', 'status' => 1, 'district_code' => 'NO', 'created_at' => now()],
            ['code' => 'RM1', 'name' => 'Baghaichari', 'status' => 1, 'district_code' => 'RM', 'created_at' => now()],
            ['code' => 'RM2', 'name' => 'Barkal', 'status' => 1, 'district_code' => 'RM', 'created_at' => now()],
            ['code' => 'RM3', 'name' => 'Belaichari', 'status' => 1, 'district_code' => 'RM', 'created_at' => now()],
            ['code' => 'RM4', 'name' => 'Juraichari', 'status' => 1, 'district_code' => 'RM', 'created_at' => now()],
            ['code' => 'RM5', 'name' => 'Kaptai', 'status' => 1, 'district_code' => 'RM', 'created_at' => now()],
            ['code' => 'RM6', 'name' => 'Kaukhali', 'status' => 1, 'district_code' => 'RM', 'created_at' => now()],
            ['code' => 'RM7', 'name' => 'Langadu', 'status' => 1, 'district_code' => 'RM', 'created_at' => now()],
            ['code' => 'RM8', 'name' => 'Nanniarchar', 'status' => 1, 'district_code' => 'RM', 'created_at' => now()],
            ['code' => 'RM9', 'name' => 'Rajosthali', 'status' => 1, 'district_code' => 'RM', 'created_at' => now()],
            ['code' => 'RM10', 'name' => 'Rangamati Sadar', 'status' => 1, 'district_code' => 'RM', 'created_at' => now()],
            ['code' => 'CG1', 'name' => 'Anwara', 'status' => 1, 'district_code' => 'CG', 'created_at' => now()],
            ['code' => 'CG2', 'name' => 'Banskhali', 'status' => 1, 'district_code' => 'CG', 'created_at' => now()],
            ['code' => 'CG3', 'name' => 'Boalkhali', 'status' => 1, 'district_code' => 'CG', 'created_at' => now()],
            ['code' => 'CG4', 'name' => 'Chandanish', 'status' => 1, 'district_code' => 'CG', 'created_at' => now()],
            ['code' => 'CG5', 'name' => 'Fatikchari', 'status' => 1, 'district_code' => 'CG', 'created_at' => now()],
            ['code' => 'CG6', 'name' => 'Hathazari', 'status' => 1, 'district_code' => 'CG', 'created_at' => now()],
            ['code' => 'CG7', 'name' => 'Karnaphuli', 'status' => 1, 'district_code' => 'CG', 'created_at' => now()],
            ['code' => 'CG8', 'name' => 'Lohagara', 'status' => 1, 'district_code' => 'CG', 'created_at' => now()],
            ['code' => 'CG9', 'name' => 'Mirsharai', 'status' => 1, 'district_code' => 'CG', 'created_at' => now()],
            ['code' => 'CG10', 'name' => 'Patiya', 'status' => 1, 'district_code' => 'CG', 'created_at' => now()],
            ['code' => 'CG11', 'name' => 'Rangunia', 'status' => 1, 'district_code' => 'CG', 'created_at' => now()],
            ['code' => 'CG12', 'name' => 'Raojan', 'status' => 1, 'district_code' => 'CG', 'created_at' => now()],
            ['code' => 'CG13', 'name' => 'Sandwip', 'status' => 1, 'district_code' => 'CG', 'created_at' => now()],
            ['code' => 'CG14', 'name' => 'Satkania', 'status' => 1, 'district_code' => 'CG', 'created_at' => now()],
            ['code' => 'CG15', 'name' => 'Sitakunda', 'status' => 1, 'district_code' => 'CG', 'created_at' => now()],
            ['code' => 'CG16', 'name' => 'Immigration (Port)', 'status' => 1, 'district_code' => 'CG', 'created_at' => now()],
            ['code' => 'CG17', 'name' => 'Bayazid Bostami', 'status' => 1, 'district_code' => 'CG', 'created_at' => now()],
            ['code' => 'CG18', 'name' => 'Kotwali', 'status' => 1, 'district_code' => 'CG', 'created_at' => now()],
            ['code' => 'CG19', 'name' => 'Bakolia', 'status' => 1, 'district_code' => 'CG', 'created_at' => now()],
            ['code' => 'CG20', 'name' => 'Port', 'status' => 1, 'district_code' => 'CG', 'created_at' => now()],
            ['code' => 'CG21', 'name' => 'Doublemooring', 'status' => 1, 'district_code' => 'CG', 'created_at' => now()],
            ['code' => 'CG22', 'name' => 'Khulshi', 'status' => 1, 'district_code' => 'CG', 'created_at' => now()],
            ['code' => 'CG23', 'name' => 'Panchlaish', 'status' => 1, 'district_code' => 'CG', 'created_at' => now()],
            ['code' => 'CG24', 'name' => 'Chandgaon', 'status' => 1, 'district_code' => 'CG', 'created_at' => now()],
            ['code' => 'CG25', 'name' => 'Halishahar', 'status' => 1, 'district_code' => 'CG', 'created_at' => now()],
            ['code' => 'CG26', 'name' => 'Pahartali', 'status' => 1, 'district_code' => 'CG', 'created_at' => now()],
            ['code' => 'CG27', 'name' => 'Bandar', 'status' => 1, 'district_code' => 'CG', 'created_at' => now()],
            ['code' => 'CG28', 'name' => 'Patenga', 'status' => 1, 'district_code' => 'CG', 'created_at' => now()],
            ['code' => 'CG29', 'name' => 'Karnophuli', 'status' => 1, 'district_code' => 'CG', 'created_at' => now()],
            ['code' => 'CB1', 'name' => 'Chakoria', 'status' => 1, 'district_code' => 'CB', 'created_at' => now()],
            ['code' => 'CB2', 'name' => 'Cox\'S Bazar Sadar', 'status' => 1, 'district_code' => 'CB', 'created_at' => now()],
            ['code' => 'CB3', 'name' => 'Kutubdia', 'status' => 1, 'district_code' => 'CB', 'created_at' => now()],
            ['code' => 'CB4', 'name' => 'Moheskhali', 'status' => 1, 'district_code' => 'CB', 'created_at' => now()],
            ['code' => 'CB5', 'name' => 'Pekua', 'status' => 1, 'district_code' => 'CB', 'created_at' => now()],
            ['code' => 'CB6', 'name' => 'Ramu', 'status' => 1, 'district_code' => 'CB', 'created_at' => now()],
            ['code' => 'CB7', 'name' => 'Teknaf', 'status' => 1, 'district_code' => 'CB', 'created_at' => now()],
            ['code' => 'CB8', 'name' => 'Ukhiya', 'status' => 1, 'district_code' => 'CB', 'created_at' => now()],
            ['code' => 'GZ1', 'name' => 'Gazipur Sadar', 'status' => 1, 'district_code' => 'GZ', 'created_at' => now()],
            ['code' => 'GZ2', 'name' => 'Tongi East', 'status' => 1, 'district_code' => 'GZ', 'created_at' => now()],
            ['code' => 'GZ3', 'name' => 'Tongi West', 'status' => 1, 'district_code' => 'GZ', 'created_at' => now()],
            ['code' => 'GZ4', 'name' => 'Gacha', 'status' => 1, 'district_code' => 'GZ', 'created_at' => now()],
            ['code' => 'GZ5', 'name' => 'Bason', 'status' => 1, 'district_code' => 'GZ', 'created_at' => now()],
            ['code' => 'GZ6', 'name' => 'Konabari', 'status' => 1, 'district_code' => 'GZ', 'created_at' => now()],
            ['code' => 'GZ7', 'name' => 'Kashimpur', 'status' => 1, 'district_code' => 'GZ', 'created_at' => now()],
            ['code' => 'GZ8', 'name' => 'Pubail', 'status' => 1, 'district_code' => 'GZ', 'created_at' => now()],
            ['code' => 'GZ9', 'name' => 'Kalikoir', 'status' => 1, 'district_code' => 'GZ', 'created_at' => now()],
            ['code' => 'GZ10', 'name' => 'Sreepur', 'status' => 1, 'district_code' => 'GZ', 'created_at' => now()],
            ['code' => 'GZ11', 'name' => 'Kapashia', 'status' => 1, 'district_code' => 'GZ', 'created_at' => now()],
            ['code' => 'GZ12', 'name' => 'Kaliganj', 'status' => 1, 'district_code' => 'GZ', 'created_at' => now()],
            ['code' => 'GZ13', 'name' => 'Joydevpur', 'status' => 1, 'district_code' => 'GZ', 'created_at' => now()],
            ['code' => 'GZ14', 'name' => 'Tongi', 'status' => 1, 'district_code' => 'GZ', 'created_at' => now()],
            ['code' => 'NG1', 'name' => 'Narayanganj Sadar', 'status' => 1, 'district_code' => 'NG', 'created_at' => now()],
            ['code' => 'NG2', 'name' => 'Fatulla', 'status' => 1, 'district_code' => 'NG', 'created_at' => now()],
            ['code' => 'NG3', 'name' => 'Siddhirganj', 'status' => 1, 'district_code' => 'NG', 'created_at' => now()],
            ['code' => 'NG4', 'name' => 'Bandar', 'status' => 1, 'district_code' => 'NG', 'created_at' => now()],
            ['code' => 'NG5', 'name' => 'Sonargaon', 'status' => 1, 'district_code' => 'NG', 'created_at' => now()],
            ['code' => 'NG6', 'name' => 'Rupganj', 'status' => 1, 'district_code' => 'NG', 'created_at' => now()],
            ['code' => 'NG7', 'name' => 'Araihazar', 'status' => 1, 'district_code' => 'NG', 'created_at' => now()],
            ['code' => 'MG1', 'name' => 'Manikganj Sadar', 'status' => 1, 'district_code' => 'MG', 'created_at' => now()],
            ['code' => 'MG2', 'name' => 'Singair', 'status' => 1, 'district_code' => 'MG', 'created_at' => now()],
            ['code' => 'MG3', 'name' => 'Saturia', 'status' => 1, 'district_code' => 'MG', 'created_at' => now()],
            ['code' => 'MG4', 'name' => 'Ghior', 'status' => 1, 'district_code' => 'MG', 'created_at' => now()],
            ['code' => 'MG5', 'name' => 'Shivaloy', 'status' => 1, 'district_code' => 'MG', 'created_at' => now()],
            ['code' => 'MG6', 'name' => 'Daulatpur', 'status' => 1, 'district_code' => 'MG', 'created_at' => now()],
            ['code' => 'MG7', 'name' => 'Harirampur', 'status' => 1, 'district_code' => 'MG', 'created_at' => now()],
            ['code' => 'TA1', 'name' => 'Tangail Sadar', 'status' => 1, 'district_code' => 'TA', 'created_at' => now()],
            ['code' => 'TA2', 'name' => 'Kalihati', 'status' => 1, 'district_code' => 'TA', 'created_at' => now()],
            ['code' => 'TA3', 'name' => 'Ghatail', 'status' => 1, 'district_code' => 'TA', 'created_at' => now()],
            ['code' => 'TA4', 'name' => 'Basail', 'status' => 1, 'district_code' => 'TA', 'created_at' => now()],
            ['code' => 'TA5', 'name' => 'Gopalpur', 'status' => 1, 'district_code' => 'TA', 'created_at' => now()],
            ['code' => 'TA6', 'name' => 'Mirzapur', 'status' => 1, 'district_code' => 'TA', 'created_at' => now()],
            ['code' => 'TA7', 'name' => 'Bhuyapur', 'status' => 1, 'district_code' => 'TA', 'created_at' => now()],
            ['code' => 'TA8', 'name' => 'Nagarpur', 'status' => 1, 'district_code' => 'TA', 'created_at' => now()],
            ['code' => 'TA9', 'name' => 'Madhupur', 'status' => 1, 'district_code' => 'TA', 'created_at' => now()],
            ['code' => 'TA10', 'name' => 'Sakhipur', 'status' => 1, 'district_code' => 'TA', 'created_at' => now()],
            ['code' => 'TA11', 'name' => 'Delduar', 'status' => 1, 'district_code' => 'TA', 'created_at' => now()],
            ['code' => 'TA12', 'name' => 'Dhanbari', 'status' => 1, 'district_code' => 'TA', 'created_at' => now()],
            ['code' => 'MP1', 'name' => 'Madaripur Sadar', 'status' => 1, 'district_code' => 'MP', 'created_at' => now()],
            ['code' => 'MP2', 'name' => 'Kalkini', 'status' => 1, 'district_code' => 'MP', 'created_at' => now()],
            ['code' => 'MP3', 'name' => 'Rajoir', 'status' => 1, 'district_code' => 'MP', 'created_at' => now()],
            ['code' => 'MP4', 'name' => 'Shibchar', 'status' => 1, 'district_code' => 'MP', 'created_at' => now()],
            ['code' => 'MP5', 'name' => 'Dasar', 'status' => 1, 'district_code' => 'MP', 'created_at' => now()],
            ['code' => 'NS1', 'name' => 'Narsingdi Sadar', 'status' => 1, 'district_code' => 'NS', 'created_at' => now()],
            ['code' => 'NS2', 'name' => 'Belabo', 'status' => 1, 'district_code' => 'NS', 'created_at' => now()],
            ['code' => 'NS3', 'name' => 'Monohardi', 'status' => 1, 'district_code' => 'NS', 'created_at' => now()],
            ['code' => 'NS4', 'name' => 'Palash', 'status' => 1, 'district_code' => 'NS', 'created_at' => now()],
            ['code' => 'NS5', 'name' => 'Raipura', 'status' => 1, 'district_code' => 'NS', 'created_at' => now()],
            ['code' => 'NS6', 'name' => 'Shibpur', 'status' => 1, 'district_code' => 'NS', 'created_at' => now()],
            ['code' => 'KI1', 'name' => 'Ashtagram', 'status' => 1, 'district_code' => 'KI', 'created_at' => now()],
            ['code' => 'KI2', 'name' => 'Itna', 'status' => 1, 'district_code' => 'KI', 'created_at' => now()],
            ['code' => 'KI3', 'name' => 'Katiyadi', 'status' => 1, 'district_code' => 'KI', 'created_at' => now()],
            ['code' => 'KI4', 'name' => 'Karimganj', 'status' => 1, 'district_code' => 'KI', 'created_at' => now()],
            ['code' => 'KI5', 'name' => 'Kishoreganj Sadar', 'status' => 1, 'district_code' => 'KI', 'created_at' => now()],
            ['code' => 'KI6', 'name' => 'Kuliachar', 'status' => 1, 'district_code' => 'KI', 'created_at' => now()],
            ['code' => 'KI7', 'name' => 'Tarail', 'status' => 1, 'district_code' => 'KI', 'created_at' => now()],
            ['code' => 'KI8', 'name' => 'Nikli', 'status' => 1, 'district_code' => 'KI', 'created_at' => now()],
            ['code' => 'KI9', 'name' => 'Pakundia', 'status' => 1, 'district_code' => 'KI', 'created_at' => now()],
            ['code' => 'KI10', 'name' => 'Bajitpur', 'status' => 1, 'district_code' => 'KI', 'created_at' => now()],
            ['code' => 'KI11', 'name' => 'Bhairav', 'status' => 1, 'district_code' => 'KI', 'created_at' => now()],
            ['code' => 'KI12', 'name' => 'Mithamain', 'status' => 1, 'district_code' => 'KI', 'created_at' => now()],
            ['code' => 'KI13', 'name' => 'Hossainpur', 'status' => 1, 'district_code' => 'KI', 'created_at' => now()],
            ['code' => 'MU1', 'name' => 'Munshiganj Sadar', 'status' => 1, 'district_code' => 'MU', 'created_at' => now()],
            ['code' => 'MU2', 'name' => 'Tongjibari', 'status' => 1, 'district_code' => 'MU', 'created_at' => now()],
            ['code' => 'MU3', 'name' => 'Srinagar', 'status' => 1, 'district_code' => 'MU', 'created_at' => now()],
            ['code' => 'MU4', 'name' => 'Lauhjong', 'status' => 1, 'district_code' => 'MU', 'created_at' => now()],
            ['code' => 'MU5', 'name' => 'Ghazaria', 'status' => 1, 'district_code' => 'MU', 'created_at' => now()],
            ['code' => 'MU6', 'name' => 'Sirajdikhan', 'status' => 1, 'district_code' => 'MU', 'created_at' => now()],
            ['code' => 'RB1', 'name' => 'Baliakandi', 'status' => 1, 'district_code' => 'RB', 'created_at' => now()],
            ['code' => 'RB2', 'name' => 'Goalanda', 'status' => 1, 'district_code' => 'RB', 'created_at' => now()],
            ['code' => 'RB3', 'name' => 'Pangsha', 'status' => 1, 'district_code' => 'RB', 'created_at' => now()],
            ['code' => 'RB4', 'name' => 'Kalukhali', 'status' => 1, 'district_code' => 'RB', 'created_at' => now()],
            ['code' => 'RB5', 'name' => 'Rajbari Sadar', 'status' => 1, 'district_code' => 'RB', 'created_at' => now()],
            ['code' => 'SP1', 'name' => 'Shariatpur Sadar', 'status' => 1, 'district_code' => 'SP', 'created_at' => now()],
            ['code' => 'SP2', 'name' => 'Damudya', 'status' => 1, 'district_code' => 'SP', 'created_at' => now()],
            ['code' => 'SP3', 'name' => 'Naria', 'status' => 1, 'district_code' => 'SP', 'created_at' => now()],
            ['code' => 'SP4', 'name' => 'Zanjira', 'status' => 1, 'district_code' => 'SP', 'created_at' => now()],
            ['code' => 'SP5', 'name' => 'Bhedarganj', 'status' => 1, 'district_code' => 'SP', 'created_at' => now()],
            ['code' => 'SP6', 'name' => 'Gosairhat', 'status' => 1, 'district_code' => 'SP', 'created_at' => now()],
            ['code' => 'FP1', 'name' => 'Alfadanga', 'status' => 1, 'district_code' => 'FP', 'created_at' => now()],
            ['code' => 'FP2', 'name' => 'Bhanga', 'status' => 1, 'district_code' => 'FP', 'created_at' => now()],
            ['code' => 'FP3', 'name' => 'Boalmari', 'status' => 1, 'district_code' => 'FP', 'created_at' => now()],
            ['code' => 'FP4', 'name' => 'Charbhadrasan', 'status' => 1, 'district_code' => 'FP', 'created_at' => now()],
            ['code' => 'FP5', 'name' => 'Faridpur Sadar', 'status' => 1, 'district_code' => 'FP', 'created_at' => now()],
            ['code' => 'FP6', 'name' => 'Madhukhali', 'status' => 1, 'district_code' => 'FP', 'created_at' => now()],
            ['code' => 'FP7', 'name' => 'Nagarkanda', 'status' => 1, 'district_code' => 'FP', 'created_at' => now()],
            ['code' => 'FP8', 'name' => 'Sadarpur', 'status' => 1, 'district_code' => 'FP', 'created_at' => now()],
            ['code' => 'FP9', 'name' => 'Saltha', 'status' => 1, 'district_code' => 'FP', 'created_at' => now()],
            ['code' => 'DH1', 'name' => 'Turag', 'status' => 1, 'district_code' => 'DH', 'created_at' => now()],
            ['code' => 'DH2', 'name' => 'Uttara (West)', 'status' => 1, 'district_code' => 'DH', 'created_at' => now()],
            ['code' => 'DH3', 'name' => 'Uttara (East)/ Uttara Model', 'status' => 1, 'district_code' => 'DH', 'created_at' => now()],
            ['code' => 'DH4', 'name' => 'Uttar Khan', 'status' => 1, 'district_code' => 'DH', 'created_at' => now()],
            ['code' => 'DH5', 'name' => 'Dakshin Khan', 'status' => 1, 'district_code' => 'DH', 'created_at' => now()],
            ['code' => 'DH6', 'name' => 'Airport', 'status' => 1, 'district_code' => 'DH', 'created_at' => now()],
            ['code' => 'DH7', 'name' => 'Khilkhet', 'status' => 1, 'district_code' => 'DH', 'created_at' => now()],
            ['code' => 'DH8', 'name' => 'Bhatara', 'status' => 1, 'district_code' => 'DH', 'created_at' => now()],
            ['code' => 'DH9', 'name' => 'Badda', 'status' => 1, 'district_code' => 'DH', 'created_at' => now()],
            ['code' => 'DH10', 'name' => 'Gulshan', 'status' => 1, 'district_code' => 'DH', 'created_at' => now()],
            ['code' => 'DH11', 'name' => 'Banani', 'status' => 1, 'district_code' => 'DH', 'created_at' => now()],
            ['code' => 'DH12', 'name' => 'Cantonment', 'status' => 1, 'district_code' => 'DH', 'created_at' => now()],
            ['code' => 'DH13', 'name' => 'Hatirjheel', 'status' => 1, 'district_code' => 'DH', 'created_at' => now()],
            ['code' => 'DH14', 'name' => 'Tejgaon Industrial Area', 'status' => 1, 'district_code' => 'DH', 'created_at' => now()],
            ['code' => 'DH15', 'name' => 'Tejgaon', 'status' => 1, 'district_code' => 'DH', 'created_at' => now()],
            ['code' => 'DH16', 'name' => 'Sherbangla Nagar', 'status' => 1, 'district_code' => 'DH', 'created_at' => now()],
            ['code' => 'DH17', 'name' => 'Mohammadpur', 'status' => 1, 'district_code' => 'DH', 'created_at' => now()],
            ['code' => 'DH18', 'name' => 'Adabar', 'status' => 1, 'district_code' => 'DH', 'created_at' => now()],
            ['code' => 'DH19', 'name' => 'Vashantek', 'status' => 1, 'district_code' => 'DH', 'created_at' => now()],
            ['code' => 'DH20', 'name' => 'Kafrul', 'status' => 1, 'district_code' => 'DH', 'created_at' => now()],
            ['code' => 'DH21', 'name' => 'Mirpur model', 'status' => 1, 'district_code' => 'DH', 'created_at' => now()],
            ['code' => 'DH22', 'name' => 'Pallabi', 'status' => 1, 'district_code' => 'DH', 'created_at' => now()],
            ['code' => 'DH23', 'name' => 'Daruchalam', 'status' => 1, 'district_code' => 'DH', 'created_at' => now()],
            ['code' => 'DH24', 'name' => 'Shah Ali', 'status' => 1, 'district_code' => 'DH', 'created_at' => now()],
            ['code' => 'DH25', 'name' => 'Rupnagar', 'status' => 1, 'district_code' => 'DH', 'created_at' => now()],
            ['code' => 'DH26', 'name' => 'Ramana Model', 'status' => 1, 'district_code' => 'DH', 'created_at' => now()],
            ['code' => 'DH27', 'name' => 'Shahbagh', 'status' => 1, 'district_code' => 'DH', 'created_at' => now()],
            ['code' => 'DH28', 'name' => 'Kalabagan', 'status' => 1, 'district_code' => 'DH', 'created_at' => now()],
            ['code' => 'DH29', 'name' => 'New Market', 'status' => 1, 'district_code' => 'DH', 'created_at' => now()],
            ['code' => 'DH30', 'name' => 'Dhanmondi', 'status' => 1, 'district_code' => 'DH', 'created_at' => now()],
            ['code' => 'DH31', 'name' => 'Hazaribagh', 'status' => 1, 'district_code' => 'DH', 'created_at' => now()],
            ['code' => 'DH32', 'name' => 'Motijheel', 'status' => 1, 'district_code' => 'DH', 'created_at' => now()],
            ['code' => 'DH33', 'name' => 'Paltan Model', 'status' => 1, 'district_code' => 'DH', 'created_at' => now()],
            ['code' => 'DH34', 'name' => 'Shahjahanpur', 'status' => 1, 'district_code' => 'DH', 'created_at' => now()],
            ['code' => 'DH35', 'name' => 'Sabujbag', 'status' => 1, 'district_code' => 'DH', 'created_at' => now()],
            ['code' => 'DH36', 'name' => 'Mugda', 'status' => 1, 'district_code' => 'DH', 'created_at' => now()],
            ['code' => 'DH37', 'name' => 'Khilgaon', 'status' => 1, 'district_code' => 'DH', 'created_at' => now()],
            ['code' => 'DH38', 'name' => 'Rampura', 'status' => 1, 'district_code' => 'DH', 'created_at' => now()],
            ['code' => 'DH39', 'name' => 'Wari', 'status' => 1, 'district_code' => 'DH', 'created_at' => now()],
            ['code' => 'DH40', 'name' => 'Gandaria', 'status' => 1, 'district_code' => 'DH', 'created_at' => now()],
            ['code' => 'DH41', 'name' => 'Shyampur', 'status' => 1, 'district_code' => 'DH', 'created_at' => now()],
            ['code' => 'DH42', 'name' => 'Kadam Toli', 'status' => 1, 'district_code' => 'DH', 'created_at' => now()],
            ['code' => 'DH43', 'name' => 'Demra', 'status' => 1, 'district_code' => 'DH', 'created_at' => now()],
            ['code' => 'DH44', 'name' => 'Jatrabari', 'status' => 1, 'district_code' => 'DH', 'created_at' => now()],
            ['code' => 'DH45', 'name' => 'Kotwali', 'status' => 1, 'district_code' => 'DH', 'created_at' => now()],
            ['code' => 'DH46', 'name' => 'Sutrapur', 'status' => 1, 'district_code' => 'DH', 'created_at' => now()],
            ['code' => 'DH47', 'name' => 'Bangshal', 'status' => 1, 'district_code' => 'DH', 'created_at' => now()],
            ['code' => 'DH48', 'name' => 'Chowkazar', 'status' => 1, 'district_code' => 'DH', 'created_at' => now()],
            ['code' => 'DH49', 'name' => 'Lalbagh', 'status' => 1, 'district_code' => 'DH', 'created_at' => now()],
            ['code' => 'DH50', 'name' => 'Kamrangirchar', 'status' => 1, 'district_code' => 'DH', 'created_at' => now()],
            ['code' => 'DH51', 'name' => 'Savar', 'status' => 1, 'district_code' => 'DH', 'created_at' => now()],
            ['code' => 'DH52', 'name' => 'Dhamrai', 'status' => 1, 'district_code' => 'DH', 'created_at' => now()],
            ['code' => 'DH53', 'name' => 'Keraniganj', 'status' => 1, 'district_code' => 'DH', 'created_at' => now()],
            ['code' => 'DH54', 'name' => 'Nawabganj', 'status' => 1, 'district_code' => 'DH', 'created_at' => now()],
            ['code' => 'DH55', 'name' => 'Dohar', 'status' => 1, 'district_code' => 'DH', 'created_at' => now()],
            ['code' => 'DH56', 'name' => 'Ashulia', 'status' => 1, 'district_code' => 'DH', 'created_at' => now()],
            ['code' => 'DH57', 'name' => 'South Keraniganj', 'status' => 1, 'district_code' => 'DH', 'created_at' => now()],
            ['code' => 'JP1', 'name' => 'Bakshiganj', 'status' => 1, 'district_code' => 'JP', 'created_at' => now()],
            ['code' => 'JP2', 'name' => 'Dewanganj', 'status' => 1, 'district_code' => 'JP', 'created_at' => now()],
            ['code' => 'JP3', 'name' => 'Islampur', 'status' => 1, 'district_code' => 'JP', 'created_at' => now()],
            ['code' => 'JP4', 'name' => 'Jamalpur Sadar', 'status' => 1, 'district_code' => 'JP', 'created_at' => now()],
            ['code' => 'JP5', 'name' => 'Madarganj', 'status' => 1, 'district_code' => 'JP', 'created_at' => now()],
            ['code' => 'JP6', 'name' => 'Melendah', 'status' => 1, 'district_code' => 'JP', 'created_at' => now()],
            ['code' => 'JP7', 'name' => 'Sarishabari', 'status' => 1, 'district_code' => 'JP', 'created_at' => now()],
            ['code' => 'MS1', 'name' => 'Bhaluka', 'status' => 1, 'district_code' => 'MS', 'created_at' => now()],
            ['code' => 'MS2', 'name' => 'Dhobaura', 'status' => 1, 'district_code' => 'MS', 'created_at' => now()],
            ['code' => 'MS3', 'name' => 'Fulbaria', 'status' => 1, 'district_code' => 'MS', 'created_at' => now()],
            ['code' => 'MS4', 'name' => 'Gaffargaon', 'status' => 1, 'district_code' => 'MS', 'created_at' => now()],
            ['code' => 'MS5', 'name' => 'Gouripur', 'status' => 1, 'district_code' => 'MS', 'created_at' => now()],
            ['code' => 'MS6', 'name' => 'Haluaghat', 'status' => 1, 'district_code' => 'MS', 'created_at' => now()],
            ['code' => 'MS7', 'name' => 'Ishwarganj', 'status' => 1, 'district_code' => 'MS', 'created_at' => now()],
            ['code' => 'MS8', 'name' => 'Muktagacha', 'status' => 1, 'district_code' => 'MS', 'created_at' => now()],
            ['code' => 'MS9', 'name' => 'Mymensingh Sadar', 'status' => 1, 'district_code' => 'MS', 'created_at' => now()],
            ['code' => 'MS10', 'name' => 'Nandail', 'status' => 1, 'district_code' => 'MS', 'created_at' => now()],
            ['code' => 'MS11', 'name' => 'Phulpur', 'status' => 1, 'district_code' => 'MS', 'created_at' => now()],
            ['code' => 'MS12', 'name' => 'Railway Station', 'status' => 1, 'district_code' => 'MS', 'created_at' => now()],
            ['code' => 'MS13', 'name' => 'Tarakanda', 'status' => 1, 'district_code' => 'MS', 'created_at' => now()],
            ['code' => 'MS14', 'name' => 'Trishal', 'status' => 1, 'district_code' => 'MS', 'created_at' => now()],
            ['code' => 'NK1', 'name' => 'Atpara', 'status' => 1, 'district_code' => 'NK', 'created_at' => now()],
            ['code' => 'NK2', 'name' => 'Barhatta', 'status' => 1, 'district_code' => 'NK', 'created_at' => now()],
            ['code' => 'NK3', 'name' => 'Durgapur', 'status' => 1, 'district_code' => 'NK', 'created_at' => now()],
            ['code' => 'NK4', 'name' => 'Kalmakanda', 'status' => 1, 'district_code' => 'NK', 'created_at' => now()],
            ['code' => 'NK5', 'name' => 'Kendua', 'status' => 1, 'district_code' => 'NK', 'created_at' => now()],
            ['code' => 'NK6', 'name' => 'Khaliajuri', 'status' => 1, 'district_code' => 'NK', 'created_at' => now()],
            ['code' => 'NK7', 'name' => 'Madan', 'status' => 1, 'district_code' => 'NK', 'created_at' => now()],
            ['code' => 'NK8', 'name' => 'Mohanganj', 'status' => 1, 'district_code' => 'NK', 'created_at' => now()],
            ['code' => 'NK9', 'name' => 'Netrakona Sadar', 'status' => 1, 'district_code' => 'NK', 'created_at' => now()],
            ['code' => 'NK10', 'name' => 'Purbadhala', 'status' => 1, 'district_code' => 'NK', 'created_at' => now()],
            ['code' => 'SH1', 'name' => 'Jhenaigati', 'status' => 1, 'district_code' => 'SH', 'created_at' => now()],
            ['code' => 'SH2', 'name' => 'Nakla', 'status' => 1, 'district_code' => 'SH', 'created_at' => now()],
            ['code' => 'SH3', 'name' => 'Nalitabari', 'status' => 1, 'district_code' => 'SH', 'created_at' => now()],
            ['code' => 'SH4', 'name' => 'Sherpur Sadar', 'status' => 1, 'district_code' => 'SH', 'created_at' => now()],
            ['code' => 'SH5', 'name' => 'Shrivardi', 'status' => 1, 'district_code' => 'SH', 'created_at' => now()],
            ['code' => 'GP1', 'name' => 'Gopalganj Sadar', 'status' => 1, 'district_code' => 'GP', 'created_at' => now()],
            ['code' => 'GP2', 'name' => 'Tungipara', 'status' => 1, 'district_code' => 'GP', 'created_at' => now()],
            ['code' => 'GP3', 'name' => 'Kotalipara', 'status' => 1, 'district_code' => 'GP', 'created_at' => now()],
            ['code' => 'GP4', 'name' => 'Kashiani', 'status' => 1, 'district_code' => 'GP', 'created_at' => now()],
            ['code' => 'GP5', 'name' => 'Maksudpur', 'status' => 1, 'district_code' => 'GP', 'created_at' => now()],

        ];

        foreach (array_chunk($thanas, 50) as $chunk) {
            DB::table('thanas')->insert($chunk);
        }
    }
}
