<?php

namespace App\Http\Resources\Tenant;

use Illuminate\Http\Resources\Json\JsonResource;

class TenantTripResource extends JsonResource
{
    public function toArray($request): array
    {
        return [
            'id' => $this->id,
            'added_by' => $this->added_by,
            'updated_by' => $this->updated_by,
            'date' => $this->date,
            'customer_id' => $this->customer_id,
            'customer' => $this->customer,
            'office_id' => $this->office_id,
            'office' => $this->office,
            'branch' => $this->branch,
            'load_area_id' => $this->load_area_id,
            'load_point_id' => $this->load_area_id,
            'load_area_name' => $this->load_area_name,
            'load_area_address' => $this->load_area_address,
            'load_area' => $this->load_area,
            'load_point' => $this->load_point,
            'unload_area_id' => $this->unload_area_id,
            'unload_point_id' => $this->unload_area_id,
            'unload_area' => $this->unload_area,
            'unload_point' => $this->unload_point,
            'trip_type' => $this->trip_type,
            'additional_unload_point' => $this->additional_unload_point,
            'sender_name' => $this->sender_name,
            'product_details' => $this->product_details,
            'transport_type' => $this->transport_type,
            'vendor_id' => $this->vendor_id,
            'vendor' => $this->vendor,
            'vehicle_id' => $this->vehicle_id,
            'vehicle' => $this->vehicle,
            'rent_vehicle_id' => $this->rent_vehicle_id,
            'rent_vehicle' => $this->rent_vehicle,
            'vehicle_no' => $this->vehicle_no,
            'driver_id' => $this->driver_id,
            'driver_name' => $this->driver_name,
            'driver' => $this->driver,
            'helper_id' => $this->helper_id,
            'helper' => $this->helper,
            'supervisor_id' => $this->supervisor_id,
            'supervisor' => $this->supervisor,
            'vehicle_category_id' => $this->vehicle_category_id,
            'vehicle_category' => $this->vehicle_category,
            'vehicle_size_id' => $this->vehicle_size_id,
            'vehicle_size' => $this->vehicle_size,
            'challan_no' => $this->challan_no,
            'total_rent_bill_amount' => $this->total_rent_bill_amount,
            'rent_advance' => $this->rent_advance,
            'rent_due_amount' => $this->rent_due_amount,
            'rent_payment_status' => $this->rent_payment_status,
            'total_cost' => $this->total_cost,
            'profit' => $this->profit,
            'odometer_start_km' => $this->odometer_start_km,
            'odometer_end_km' => $this->odometer_end_km,
            'running_km' => $this->running_km,
            'vehicle_kpl' => $this->vehicle_kpl,
            'fuel_quantity_liter' => $this->fuel_quantity_liter,
            'fuel_cost_per_liter' => $this->fuel_cost_per_liter,
            'fuel_supplier_id' => $this->fuel_supplier_id,
            'fuel_supplier' => $this->fuel_supplier,
            'fuel_type' => $this->fuel_type,
            'demurrage_days' => $this->demurrage_days,
            'total_demurrage' => $this->total_demurrage,
            'demurrage_total_rent' => $this->demurrage_total_rent,
            'vendor_demurrage_days' => $this->vendor_demurrage_days,
            'vendor_total_demurrage' => $this->vendor_total_demurrage,
            'vendor_rent' => $this->vendor_rent,
            'vendor_rent_demurrage_total' => $this->vendor_rent_demurrage_total,
            'advance' => $this->advance,
            'due_amount' => $this->due_amount,
            'driver_advance' => $this->driver_advance,
            'driver_commission_percent' => $this->driver_commission_percent,
            'driver_commission_amount' => $this->driver_commission_amount,
            'fuel_cost' => $this->fuel_cost,
            'labour_cost' => $this->labour_cost,
            'toll_cost' => $this->toll_cost,
            'ferry_cost' => $this->ferry_cost,
            'police_cost' => $this->police_cost,
            'chada_cost' => $this->chada_cost,
            'parking_cost' => $this->parking_cost,
            'challan_cost' => $this->challan_cost,
            'food_cost' => $this->food_cost,
            'others_cost' => $this->others_cost,
            'night_guard' => $this->night_guard,
            'additional_load_cost' => $this->additional_load_cost,
            'total_expense' => $this->total_expense,
            'remarks' => $this->remarks,
            'status' => (int) $this->status,
            'created_at' => $this->created_at,
            'updated_at' => $this->updated_at,
        ];
    }
}
